apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started-des
  namespace: des
  labels:
    app: getting-started
    system: HACKATHON
    module: getting-started
    env: des
    group: grp01
    instance: ci-hackathon-getting-started-des-grp01-001
  annotations:
    pipeline.name: "HACKATHON-getting-started-release-des"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getting-started
      env: des
  template:
    metadata:
      labels:
        app: getting-started
        system: HACKATHON
        module: getting-started
        env: des
        group: grp01
        instance: ci-hackathon-getting-started-des-grp01-001
    spec:
      containers:
        - name: getting-started
          # tag placeholder para o primeiro apply; o deploy-des.ps1 faz 'kubectl set image'
          image: hackathon/getting-started:0.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /hello
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
