apiVersion: v1
kind: Service
metadata:
  name: getting-started-svc-prd
  namespace: prd
spec:
  selector:
    app: getting-started
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
