apiVersion: v1
kind: Service
metadata:
  name: getting-started-service
spec:
  type: NodePort
  selector:
    app: getting-started
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
